sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

# you can specify futher versions as found at http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - "4.1.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    - haxe: "3.4.7"

install:
  - haxelib install travix
  # to always use the latest version of travix comment out the previous line and uncomment the next
  # - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix node
  - haxelib run travix cpp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix java

  - haxelib run travix interp -D echoes_array_container -D echoes_profiling
  - haxelib run travix node -D echoes_array_container -D echoes_profiling
  - haxelib run travix cpp -D echoes_array_container -D echoes_profiling
  - haxelib run travix neko -D echoes_array_container -D echoes_profiling
  - haxelib run travix python -D echoes_array_container -D echoes_profiling
  - haxelib run travix java -D echoes_array_container -D echoes_profiling

  - haxelib run travix interp -D echoes_vector_container -D echoes_profiling
  - haxelib run travix node -D echoes_vector_container -D echoes_profiling
  - haxelib run travix cpp -D echoes_vector_container -D echoes_profiling
  - haxelib run travix neko -D echoes_vector_container -D echoes_profiling
  - haxelib run travix python -D echoes_vector_container -D echoes_profiling
  - haxelib run travix java -D echoes_vector_container -D echoes_profiling

  # - haxelib run travix js
  # - haxelib run travix flash
  # - haxelib run travix cs
  # - haxelib run travix php
  #v- haxelib run travix php7
  # - if [[ "$(haxe -version)" =~ ^4.* ]]; then haxelib run travix hl; fi
  # - haxelib run travix lua
